name: Build e Envio para Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      # Construir a imagem Docker
      - name: Build Docker image
        run: docker build -t lord143/proposta-api .

      # Autenticar no Docker Hub
      - name: Log in to Docker Hub
        env:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: docker login -u lord143 -p "${DOCKERHUB_TOKEN}"

      # Enviar a imagem para o Docker Hub
      - name: Push image to Docker Hub
        run: docker push lord143/proposta-api
